package com.arvindrachuri.ehtml.utils.css

object CssAttribute {
    const val PADDING = "padding"
    const val MARGIN = "margin"
    const val FONT_SIZE = "font-size"
    const val FONT_WEIGHT = "font-weight"
    const val FONT_STYLE = "font-style"
    const val FONT_FAMILY = "font-family"
    const val COLOR = "color"
    const val BACKGROUND_COLOR = "background-color"
    const val WIDTH = "width"
    const val MAX_WIDTH = "max-width"
    const val MIN_WIDTH = "min-width"
    const val HEIGHT = "height"
    const val MAX_HEIGHT = "max-height"
    const val MIN_HEIGHT = "min-height"
    const val BORDER = "border"
    const val BORDER_RADIUS = "border-radius"
    const val OPACITY = "opacity"
    const val DISPLAY = "display"
    const val LINE_HEIGHT = "line-height"
    const val LETTER_SPACING = "letter-spacing"
    const val WORD_SPACING = "word-spacing"
    const val TEXT_ALIGN = "text-align"
    const val TEXT_DECORATION = "text-decoration"
    const val TEXT_TRANSFORM = "text-transform"
    const val OVERFLOW = "overflow"
    const val OVERFLOW_X = "overflow-x"
    const val OVERFLOW_Y = "overflow-y"
    const val VERTICAL_ALIGN = "vertical-align"
    const val DIRECTION = "direction"
    const val FLOAT = "float"
    const val WHITE_SPACE = "white-space"
}
